Revert "[map] Allow std::move-ing keys into the map"
This reverts commit f657ef7e57c889309c2d9d37934368ca255f9d5b.

This breaks many compilers with messages like this:

hb-subset-plan.hh:226: undefined reference to `OT::head::tableTag'

I'm out of my depth re how to fix it.